---
- hosts: localhost
  tasks:
  - name: Create new DO Docker droplet
    digital_ocean: >
      state=present
      command=droplet
      name=ansible-tutorial
      size_id=3
      region_id=3
      image_id=10581649
      ssh_key_ids=675697


